# Generated by Django 6.0.1 on 2026-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.JSONField(default=list)),
                ("link", models.URLField(max_length=1000, unique=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(default="saramin", max_length=50)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
    ]
