# Generated by Django 6.0.1 on 2026-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="embedding",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
